version: "3.8"

services:
  searxng:
    image: "searxng/searxng:latest"
    container_name: searxng
    hostname: searxng
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
    expose:
      - 8080
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cal_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - searxng
      - proxy
    labels:
      - traefik.enable=true

  redis:
    image: "redis:alpine"
    container_name: searxng_redis
    restart: unless-stopped
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - searxng-redis:/data

volumes:
  searxng-redis:
    name: searxng-redis

networks:
  searxng:
    name: "searxng"
    ipam:
      driver: default
  # Your proxy network
  proxy:
    external: true
