http:
  services:
    searxng:
      loadBalancer:
        servers:
          - url: "http://searxng:8080" # The exposed port by searxng

  routers:
    searxng:
      rule: "Host(`your.url.here`) && Method(`GET`,`POST`,`HEAD`)"
      middlewares:
        - general_security
        - searxng_headers
      service: searxng
      entryPoints:
        # Your https entrypoint in traefik 'entryPoints'
        - "websecure"
      tls:
        # Your cert resolver in traefik 'certificatesResolvers'
        certResolver: production

  # Results in A+ grade in mozilla observatory
  middlewares:
    general_security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
    searxng_headers:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "noindex, noarchive, nofollow"
          Content-Security-Policy: "upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/searxng/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com"
          Permissions-Policy: "accelerometer=(),ambient-light-sensor=(),autoplay=(),camera=(),encrypted-media=(),focus-without-user-activation=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),speaker=(),sync-xhr=(),usb=(),vr=()"

# vim: wrap
